{% set name = "omnifit" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 61ecc0115a4c563042a3675ce818480e562d0859f4c93dd1c18cb885a343b665
  patches:
    - patch.diff

build:
  number: 0
  script: python setup.py install --offline --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
  run:
    - python
    - astropy >=1.0.0
    - matplotlib >=1.3.0
    - lmfit >=0.9.2

test:
  imports:
    - omnifit
    - omnifit.fitter
    - omnifit.spectrum
    - omnifit.utils

about:
  home: https://github.com/RiceMunk/omnifit
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Omnifit - astronomical ice spectroscopy fitting
  description: |
    At its heart Omnifit is simply a convenience tool intended to make a
    specific type of spectral analysis (that of interstellar ices) as easy as
    possible. You may have a reason to use Omnifit if you have spectroscopic
    data which you suspect contains signs of ices or  either additional
    spectroscopic data which you want to try and fit to your observed data or
    you know how to describe the shape of the suspected ice feature with an
    analytical function.
  doc_url: https://ricemunk.github.io/omnifit
  dev_url: https://github.com/RiceMunk/omnifit

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - RiceMunk
