appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: KzPnEf5MGat7zVXe+g5kMy+1JSwqJnf7QiFevE2AnTvD/lWuYLHvScXTQwzg6x4nRpbVRKB+dJlzaSNZRd5jobNtKyY4fIbxhMuQsc/O6fTlUQjCP8VU8Jy8dl/m9vZortN9p9r1t7iwz8EoT1yJL9tM70Lo3LJsASx8wTU7KZLk5LAReXdAJNZ5B1GpX3BrU7p4B4fA0l667Ko7F2yIE2Y7F2WCRZhzgFsqa72NOLQ/rEIy0A16uRrarB6jcg5iiQTzGLTsOKLClC4g8pXsmdIhsOP5mzIegzY3d6dpVdmj7gV0eoexb1BvYGX0wOInzQENUwznZ3zc2Wxjhas3posA7QXpGcibl26U+vatsA81dARJ/SbF92dHMhDScvQXmELBtc73DWZoHfLYLFO3fVcZQnYZVmkBo3bYdmynEyA3GAi+h8h9zUb612DbL3/KAVoQwYWEZEL/B0AhxY/T1rj3pqCcZRWmbIWY9hs2MSLXEaxrXzZBLeIiDehGZti41L2Q9fB/8CMjxfwz82+oua0RYC8j23USCbMt6M5c37EDTaTHZgPuU7D/9JlrBxiuSzWUnr3Nr1i4lYTILd+LlXdVOwPU53Y5IDVSNFM4QCsVAHnLaic9t0G+q7rNnpERFoJLrc8ELTXZndR8ceDbwJJ0tpw34FuDehlMmoIk8d4=}
conda_forge_output_validation: true
